import type { MetadataRoute } from "next";

// Web App Manifest (Next file-based metadata → served at /manifest.webmanifest).
// Colours are the locked brand tokens (docs/BRAND.md): red #EE2346, black
// surface #0A0A0A. Icons are generated by the route handlers under app/icons/*.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "eLanguage Center",
    short_name: "eLanguage",
    description:
      "IELTS preparation across Reading, Listening, Writing, and Speaking. AI-generated practice, AI-graded feedback.",
    id: "/",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait-primary",
    background_color: "#FFFFFF",
    theme_color: "#EE2346",
    categories: ["education"],
    icons: [
      { src: "/icons/icon-192", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icons/maskable-512", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
